networks:
  room-booking:
    driver: bridge

services:
  discovery-server:
    build: discovery-server
    image: discovery-server:latest
    container_name: discovery-server
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "8761:8761"
    environment:
      - SPRING_DISCOVERY_SERVER_HOST=discovery-server
    networks:
      - room-booking

  api-gateway:
    build: api-gateway
    image: api-gateway:latest
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      discovery-server:
        condition: service_healthy
    environment:
      - SPRING_DISCOVERY_SERVER_HOST=discovery-server
    networks:
      - room-booking

  users-service:
    build: users-service
    image: users-service:latest
    container_name: users-service
    ports:
      - "8091:8091"
    depends_on:
      api-gateway:
        condition: service_started
      discovery-server:
        condition: service_healthy
      users-service-db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://users-service-db:5432/users_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_DATASOURCE_HOST=users-service-db
      - SPRING_DATASOURCE_PORT=5432
      - SPRING_DISCOVERY_SERVER_HOST=discovery-server
      - ROOMS_SERVICE_HOST=room-service
      - ROOMS_SERVICE_PORT=8093
      - USERS_SERVICE_HOST=users-service
      - USERS_SERVICE_PORT=8091
    networks:
      - room-booking

  users-service-db:
    image: postgres:16.1
    container_name: users-service-db
    ports:
      - "5441:5432"
    environment:
      - POSTGRES_DB=users_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      start_period: 10s
      timeout: 5s
      interval: 10s
      retries: 5
    volumes:
      - users-service-db-data:/var/lib/postgresql/data
    restart: unless-stopped

    networks:
      - room-booking

  booking-service:
    build: booking-service
    image: booking-service:latest
    command: ["./wait-for.sh", "discovery-server:8761", "--", "java", "-jar", "app.jar"]
    container_name: booking-service
    ports:
      - "8092:8092"
    depends_on:
      api-gateway:
        condition: service_started
      discovery-server:
        condition: service_healthy
      booking-service-db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://booking-service-db:5432/booking_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_DATASOURCE_HOST=booking-service-db
      - SPRING_DATASOURCE_PORT=5432
      - SPRING_DISCOVERY_SERVER_HOST=discovery-server
    networks:
      - room-booking


  booking-service-db:
    image: postgres:16.1
    container_name: booking-service-db
    ports:
      - "5442:5432"
    environment:
      - POSTGRES_DB=booking_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      start_period: 10s
      timeout: 5s
      interval: 10s
      retries: 5
    volumes:
      - booking-service-db-data:/var/lib/postgresql/data

    networks:
      - room-booking

  room-service:
    build: room-service
    image: room-service:latest
    container_name: room-service
    ports:
      - "8093:8093"
    depends_on:
      api-gateway:
        condition: service_started
      discovery-server:
        condition: service_healthy
      room-service-db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://room-service-db:5432/room_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_DATASOURCE_HOST=room-service-db
      - SPRING_DATASOURCE_PORT=5432
      - SPRING_DISCOVERY_SERVER_HOST=discovery-server
    networks:
      - room-booking

  room-service-db:
    image: postgres:16.1
    container_name: room-service-db
    ports:
      - "5443:5432"
    environment:
      - POSTGRES_DB=room_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      start_period: 10s
      timeout: 5s
      interval: 10s
      retries: 5
    volumes:
      - room-service-db-data:/var/lib/postgresql/data

    networks:
      - room-booking

  notification-service:
    build: notification-service
    image: notification-service:latest
    container_name: notification-service
    ports:
      - "8094:8094"
    depends_on:
      api-gateway:
        condition: service_started
      discovery-server:
        condition: service_healthy
      notification-service-db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://notification-service-db:5432/notification_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_DATASOURCE_HOST=notification-service-db
      - SPRING_DATASOURCE_PORT=5432
      - SPRING_DISCOVERY_SERVER_HOST=discovery-server
    networks:
      - room-booking

  notification-service-db:
    image: postgres:16.1
    container_name: notification-service-db
    ports:
      - "5444:5432"
    environment:
      - POSTGRES_DB=notification_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      start_period: 10s
      timeout: 5s
      interval: 10s
      retries: 5
    volumes:
      - notification-service-db-data:/var/lib/postgresql/data
    networks:
      - room-booking

volumes:
  room-service-db-data:
  booking-service-db-data:
  users-service-db-data:
  notification-service-db-data: