server:
  port: 8091

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${SPRING_DATASOURCE_HOST:localhost}:${SPRING_DATASOURCE_PORT:5441}/users_db #jdbc:postgresql://users-service-db:5432/users_db
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
  application:
    name: users-service

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate.format_sql: true
    show-sql: true

  sql:
    init:
      mode: always

eureka:
  client:
    service-url:
      defaultZone: http://${SPRING_DISCOVERY_SERVER_HOST:localhost}:8761/eureka/
  instance:
    preferIpAddress: true

logging:
  level:
    org.springframework.orm.jpa: INFO
    org.springframework.transaction: INFO
    org.springframework.web: INFO

springdoc:
  swagger-ui:
    url: /api/v1/users/v3/api-docs
    path: /api/v1/users/swagger-ui/index.html
    tags-sorter: alpha
    operations-sorter: alpha
    #config-url: /v3/api-docs/swagger-config
    layout: StandaloneLayout
    custom-js: /swagger-ui-init.js
  api-docs:
    path: /api/v1/users/v3/api-docs

rooms:
  server:
    url: http://${ROOMS_SERVICE_HOST:localhost}:${ROOMS_SERVICE_PORT:8093}
    path: /api/v1/rooms

users:
  server:
    url: http://localhost:${USERS_SERVICE_PORT:8091}
    path: /api/v1/users

#environment:
  #- SPRING_LIQUIBASE_CHANGELOG=classpath:/db/changelog/db.changelog-master.yaml
  #- SPRING_LIQUIBASE_CONTEXTS=default