JWT_EXPIRATION_MS=1000 * 60 * 60 * 24
EMAIL_IS_ALREADY_IN_USE_EXCEPTION_MESSAGE=Email is already in use
USERNAME_IS_ALREADY_IN_USE_EXCEPTION_MESSAGE=UserName is already in use
USER_NOT_FOUND_EXCEPTION_MESSAGE=User not found
NO_USERS_FOUND_EXCEPTION_MESSAGE=No users found
CANNOT_CREATE_NEW_USER_EXCEPTION_MESSAGE=error on creating new user
INVALID_USERNAME_OR_PASSWORD_EXCEPTION_MESSAGE=Invalid username or password
USERNAME_OR_PASSWORD_IS_NULL_EXCEPTION_MESSAGE=Username or password is null
BASIC_AUTHORIZATION_HEADER_IS_MISSING_EXCEPTION_MESSAGE=Basic Authorization header is missing
DATABASE_ACCESS_EXCEPTION_MESSAGE=Unable to access database
UNABLE_TO_FETCH_USER_EXCEPTION_MESSAGE=Unable to fetch user
BAD_REQUEST_EXCEPTION_MESSAGE=Bad request
ARGUMENT_IS_NULL_EXCEPTION_MESSAGE=Argument is null
UNABLE_TO_CREATE_NEW_USER=Unable to create new user

JWT_VERIFICATION_EXCEPTION=error verification Jwt
SALT_KEY=$2a$10$bynIPMKX68HSJHkaKAZ.mO
JWT_SECRET=yourSecretKeyShouldBeLongerAndMoreComplexdwfFV_we_f34_F_F#ER#WDDWr3tr_
JWT_ISSUER=Andr33w
BASIC_AUTHORIZATION_HEADER_IS_MISSING_MESSAGE=Basic Authorization header is missing
TOKEN_VALIDATION_EXCEPTION_MESSAGE=Token is invalid
SUCCESSFUL_USER_DELETE_MESSAGE=User is delete successful
UNABLE_TO_DELETE_USER_EXCEPTION_MESSAGE=Unable to delete user
UNABLE_TO_UPDATE_USER_EXCEPTION_MESSAGE=Unable to update user
USER_ALREADY_EXISTS_EXCEPTION_MESSAGE=User already exists
UNEXPECTED_ERROR_MESSAGE=Unexpected server error
FORBIDDEN_OPERATION_EXCEPTION_MESSAGE=Operation forbidden. You don't have permission
AUTHENTICATION_EXCEPTION_MESSAGE=Error in authentication process
BEARER_AUTHORIZATION_HEADER_IS_MISSING_EXCEPTION_MESSAGE=Bearer authorization header is missing
INVALID_ARGUMENT_EXCEPTION_MESSAGE=Invalid argument
ACCESS_DENIED_MESSAGE=Access Denied!

api.server.url=http://localhost:8080
springdoc.api-docs.path=/v3/api-docs
