server:
  port: 8761

spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration

eureka:
  instance:
    hostname: ${SPRING_DISCOVERY_SERVER_HOST:localhost} #${SPRING_DISCOVERY_SERVER_HOST:discovery-server}
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${SPRING_DISCOVERY_SERVER_HOST:localhost}:8761/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    org.springframework.orm.jpa: INFO
    org.springframework.transaction: INFO
    org.springframework.web: INFO